name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate image tag
      run: echo "IMAGE_TAG=$(date +'%s')" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Login to GHCR
      run: docker login ghcr.io -u sukebenedek -p ${{ secrets.GHCR_TOKEN }}

    - name: Build and push backend
      run: |
        docker build ./backend --file ./backend/Dockerfile --tag ghcr.io/sukebenedek/countries-backend:$IMAGE_TAG
        docker push ghcr.io/sukebenedek/countries-backend:$IMAGE_TAG

    - name: Build and push frontend
      run: |
        docker build ./frontend --file ./frontend/Dockerfile --tag ghcr.io/sukebenedek/countries-frontend:$IMAGE_TAG
        docker push ghcr.io/sukebenedek/countries-frontend:$IMAGE_TAG

    - name: Update deployment.yaml with new image tags
      run: |
        sed -i 's|ghcr.io/sukebenedek/countries-backend:.*|ghcr.io/sukebenedek/countries-backend:'"$IMAGE_TAG"'|' deployment.yaml
        sed -i 's|ghcr.io/sukebenedek/countries-frontend:.*|ghcr.io/sukebenedek/countries-frontend:'"$IMAGE_TAG"'|' deployment.yaml

        git config --global user.name "sukebenedek"
        git config --global user.email "suke.benedek@students.jedlik.eu"
        git add deployment.yaml
        git commit -m "Update K8S deployment yaml file [skip ci]"
        git push

    - name: Deploy to Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.K8S_CONFIG_BASE64 }}" | base64 -d > ~/.kube/config
        kubectl apply -f deployment.yaml